CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS users;
CREATE SCHEMA IF NOT EXISTS spaces;
CREATE SCHEMA IF NOT EXISTS matchings;
CREATE SCHEMA IF NOT EXISTS alarms;
CREATE SCHEMA IF NOT EXISTS popups;
CREATE SCHEMA IF NOT EXISTS chating;
