-- ============================================================
-- SPACE AVAILABILITY (요일×시간대 반복 가용시간 템플릿)
-- 기존 spaces.space_schedules(날짜 지정 개별 예약 슬롯)와는 별개 테이블이다.
-- ============================================================
CREATE TABLE spaces.space_availabilities (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    space_id      BIGINT NOT NULL,
    day_of_week   VARCHAR(20) NOT NULL,
    start_time    TIME NOT NULL,
    end_time      TIME NOT NULL,
    is_open       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_space_availabilities PRIMARY KEY (id),
    CONSTRAINT chk_space_availabilities_day_of_week CHECK (day_of_week IN (
        'MONDAY',
        'TUESDAY',
        'WEDNESDAY',
        'THURSDAY',
        'FRIDAY',
        'SATURDAY',
        'SUNDAY'
    ))
);

CREATE INDEX idx_space_availabilities_space_id ON spaces.space_availabilities (space_id);
