-- ============================================================
-- SUGGESTION (건의함) AGGREGATE
-- ============================================================
CREATE SCHEMA IF NOT EXISTS suggestions;

CREATE TABLE suggestions.suggestions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id        VARCHAR(255) NOT NULL,
    title          VARCHAR(255) NOT NULL,
    content        TEXT NOT NULL,
    status         VARCHAR(20) NOT NULL,
    answer_content TEXT,
    answered_at    TIMESTAMP(6),
    created_at     TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_suggestions PRIMARY KEY (id),
    CONSTRAINT chk_suggestions_status CHECK (status IN ('PENDING', 'ANSWERED'))
);

CREATE INDEX idx_suggestions_user_id_created_at
    ON suggestions.suggestions (user_id, created_at DESC);

CREATE INDEX idx_suggestions_created_at
    ON suggestions.suggestions (created_at DESC);
