-- ============================================================
-- SPACE BOOKED DATE (매칭 승인 시점에 matching 모듈이 기록하는 예약 완료 날짜)
-- ============================================================
CREATE TABLE spaces.space_booked_dates (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    space_id    BIGINT NOT NULL,
    date        DATE NOT NULL,
    matching_id BIGINT NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_space_booked_dates PRIMARY KEY (id)
);

CREATE INDEX idx_space_booked_dates_space_id_date
    ON spaces.space_booked_dates (space_id, date);
