-- ============================================================
-- SCHEMAS
-- ============================================================
CREATE SCHEMA IF NOT EXISTS users;
CREATE SCHEMA IF NOT EXISTS spaces;
CREATE SCHEMA IF NOT EXISTS matchings;
CREATE SCHEMA IF NOT EXISTS alarms;
CREATE SCHEMA IF NOT EXISTS popups;
CREATE SCHEMA IF NOT EXISTS chating;

-- ============================================================
-- USER AGGREGATE
-- ============================================================
CREATE TABLE users.users (
    id             VARCHAR(255) NOT NULL,
    email          VARCHAR(255) NOT NULL,
    password       VARCHAR(255),
    auth_provider  VARCHAR(255),
    provider_id    VARCHAR(255),
    name           VARCHAR(255) NOT NULL,
    role           VARCHAR(255) NOT NULL,
    phone          VARCHAR(255),
    intro          VARCHAR(255),
    image_url      VARCHAR(2048),
    created_at     TIMESTAMP(6) NOT NULL,
    updated_at     TIMESTAMP(6) NOT NULL,
    deleted_at     TIMESTAMP(6),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_phone UNIQUE (phone),
    CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN'))
);

-- ============================================================
-- SPACE AGGREGATE
-- ============================================================
CREATE TABLE spaces.addresses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sido            VARCHAR(255) NOT NULL,
    sigungu         VARCHAR(255) NOT NULL,
    eup_myeon_dong  VARCHAR(255),
    road_address    VARCHAR(255) NOT NULL,
    jibun_address   VARCHAR(255),
    detail_address  VARCHAR(255),
    postal_code     VARCHAR(255),
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_addresses PRIMARY KEY (id)
);

CREATE TABLE spaces.spaces (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    host_id         VARCHAR(255) NOT NULL,
    address_id      BIGINT NOT NULL,
    name            VARCHAR(255) NOT NULL,
    description     TEXT,
    ai_summary      TEXT,
    thumbnail_url   VARCHAR(255) NOT NULL,
    price_per_hour  INTEGER NOT NULL,
    admin_status    VARCHAR(255) NOT NULL,
    is_active       BOOLEAN NOT NULL,
    category        VARCHAR(255) NOT NULL,
    phone           VARCHAR(255),
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    deleted_at      TIMESTAMP(6),
    CONSTRAINT pk_spaces PRIMARY KEY (id),
    CONSTRAINT chk_spaces_admin_status CHECK (admin_status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT chk_spaces_category CHECK (category IN (
        'PRACTICE_ROOM', 'STUDIO', 'MEETING_ROOM', 'PARTY_ROOM', 'CLASSROOM',
        'POPUP_STORE', 'OFFICE', 'HALL', 'CAFE', 'OTHER'
    ))
);

CREATE TABLE spaces.space_images (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    space_id   BIGINT NOT NULL,
    image_url  VARCHAR(255) NOT NULL,
    CONSTRAINT pk_space_images PRIMARY KEY (id)
);

CREATE TABLE spaces.space_schedules (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    space_id     BIGINT NOT NULL,
    start_time   TIMESTAMP(6) NOT NULL,
    end_time     TIMESTAMP(6) NOT NULL,
    is_bookable  BOOLEAN NOT NULL,
    CONSTRAINT pk_space_schedules PRIMARY KEY (id)
);

-- ============================================================
-- MATCHING AGGREGATE
-- ============================================================
CREATE TABLE matchings.matchings (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    space_id     BIGINT NOT NULL,
    host_id      VARCHAR(255) NOT NULL,
    seller_id    VARCHAR(255) NOT NULL,
    start_time   TIMESTAMP(6) NOT NULL,
    end_time     TIMESTAMP(6) NOT NULL,
    total_price  INTEGER NOT NULL,
    status       VARCHAR(255) NOT NULL,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_matchings PRIMARY KEY (id),
    CONSTRAINT chk_matchings_status CHECK (status IN ('REQUESTED', 'APPROVED', 'REJECTED', 'CANCELED'))
);

-- ============================================================
-- ALARM AGGREGATE
-- ============================================================
CREATE TABLE alarms.matchings_alarm (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id      VARCHAR(255) NOT NULL,
    matching_id  BIGINT NOT NULL,
    description  TEXT NOT NULL,
    is_read      BOOLEAN NOT NULL,
    CONSTRAINT pk_matchings_alarm PRIMARY KEY (id)
);

-- ============================================================
-- POPUP AGGREGATE
-- ============================================================
CREATE TABLE popups.popups (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    matching_id       BIGINT NOT NULL,
    space_id          BIGINT NOT NULL,
    seller_id         VARCHAR(255) NOT NULL,
    title             VARCHAR(255) NOT NULL,
    description       TEXT,
    thumbnail_url     VARCHAR(255) NOT NULL,
    ai_brand_summary  TEXT,
    start_time        TIMESTAMP(6) NOT NULL,
    end_time          TIMESTAMP(6) NOT NULL,
    view_count        INTEGER NOT NULL,
    like_count        INTEGER NOT NULL,
    created_at        TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_popups PRIMARY KEY (id),
    CONSTRAINT uk_popups_matching_id UNIQUE (matching_id)
);

-- ============================================================
-- CHAT AGGREGATE
-- ============================================================
CREATE TABLE chating.chat_rooms (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    space_id     BIGINT NOT NULL,
    host_id      VARCHAR(255) NOT NULL,
    host_name    VARCHAR(255) NOT NULL,
    seller_id    VARCHAR(255) NOT NULL,
    seller_name  VARCHAR(255) NOT NULL,
    space_name   VARCHAR(255) NOT NULL,
    created_at   TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_chat_rooms PRIMARY KEY (id)
);

CREATE TABLE chating.chat_messages (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    chat_room_id  BIGINT NOT NULL,
    sender_id     VARCHAR(255) NOT NULL,
    content       TEXT NOT NULL,
    is_read       BOOLEAN NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_chat_messages PRIMARY KEY (id)
);
