-- ============================================================
-- REVIEW AGGREGATE
-- ============================================================
CREATE SCHEMA IF NOT EXISTS reviews;

CREATE TABLE reviews.space_reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    matching_id BIGINT NOT NULL,
    space_id    BIGINT NOT NULL,
    user_id     VARCHAR(255) NOT NULL,
    rating      INTEGER NOT NULL,
    content     TEXT NOT NULL,
    like_count  INTEGER NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_space_reviews PRIMARY KEY (id),
    CONSTRAINT uk_space_reviews_matching_id UNIQUE (matching_id),
    CONSTRAINT chk_space_reviews_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE INDEX idx_space_reviews_space_id_created_at
    ON reviews.space_reviews (space_id, created_at DESC);

CREATE TABLE reviews.popup_reviews (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    popup_id             BIGINT NOT NULL,
    user_id              VARCHAR(255) NOT NULL,
    rating               INTEGER NOT NULL,
    content              TEXT NOT NULL,
    verification_type    VARCHAR(255) NOT NULL,
    verification_payload TEXT NOT NULL,
    is_verified          BOOLEAN NOT NULL,
    like_count           INTEGER NOT NULL,
    created_at           TIMESTAMP(6) NOT NULL,
    updated_at           TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_popup_reviews PRIMARY KEY (id),
    CONSTRAINT uk_popup_reviews_popup_id_user_id UNIQUE (popup_id, user_id),
    CONSTRAINT chk_popup_reviews_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT chk_popup_reviews_verification_type CHECK (verification_type IN ('QR', 'RECEIPT'))
);

CREATE INDEX idx_popup_reviews_popup_id_created_at
    ON reviews.popup_reviews (popup_id, created_at DESC);
