-- ============================================================
-- LIKE AGGREGATE
-- ============================================================
CREATE SCHEMA IF NOT EXISTS likes;

CREATE TABLE likes.popup_likes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    popup_id    BIGINT NOT NULL,
    user_id     VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_popup_likes PRIMARY KEY (id),
    CONSTRAINT uk_popup_likes_popup_id_user_id UNIQUE (popup_id, user_id)
);

CREATE INDEX idx_popup_likes_user_id_created_at
    ON likes.popup_likes (user_id, created_at DESC);
