-- ============================================================
-- SPACE LIKE COUNTER
-- ============================================================
ALTER TABLE spaces.spaces
    ADD COLUMN like_count INTEGER NOT NULL DEFAULT 0;

-- ============================================================
-- SPACE LIKE AGGREGATE
-- ============================================================
CREATE TABLE likes.space_likes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    space_id    BIGINT NOT NULL,
    user_id     VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_space_likes PRIMARY KEY (id),
    CONSTRAINT uk_space_likes_space_id_user_id UNIQUE (space_id, user_id)
);

CREATE INDEX idx_space_likes_user_id_created_at
    ON likes.space_likes (user_id, created_at DESC);

-- ============================================================
-- REVIEW LIKE AGGREGATE
-- ============================================================
CREATE TABLE likes.space_review_likes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    space_review_id BIGINT NOT NULL,
    user_id     VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_space_review_likes PRIMARY KEY (id),
    CONSTRAINT uk_space_review_likes_review_id_user_id UNIQUE (space_review_id, user_id)
);

CREATE INDEX idx_space_review_likes_user_id_created_at
    ON likes.space_review_likes (user_id, created_at DESC);

CREATE TABLE likes.popup_review_likes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    popup_review_id BIGINT NOT NULL,
    user_id     VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_popup_review_likes PRIMARY KEY (id),
    CONSTRAINT uk_popup_review_likes_review_id_user_id UNIQUE (popup_review_id, user_id)
);

CREATE INDEX idx_popup_review_likes_user_id_created_at
    ON likes.popup_review_likes (user_id, created_at DESC);
